[build-system]
requires = [
    "setuptools",
    "wheel",
    "numpy",
    "keystone-engine",
    "termcolor",
    "rich",
    "ropper",
    "capstone",
    "pefile"
]
build-backend = "setuptools.build_meta"
