name: shellcrafter CI

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
on:
  push:
    branches:
      - master
      - develop

jobs:
  publish-test-pypi:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install PyPA/Build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_TEST_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
  publish-pypi:
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/master'
      steps:
        - uses: actions/checkout@master
        - name: Set up Python 3.9
          uses: actions/setup-python@v1
          with:
            python-version: 3.9
        - name: Install PyPA/Build
          run: >-
            python -m
            pip install
            build
            --user
        - name: Build a binary wheel and a source tarball
          run: >-
            python -m
            build
            --sdist
            --wheel
            --outdir dist/
        - name: Publish distribution to PyPI
          uses: pypa/gh-action-pypi-publish@master
          with:
            password: ${{ secrets.PYPI_API_TOKEN }}
